### ISSUE TITLE
Requirement aiohttp is missing

### ISSUE THREAD

**Issue by frafra** [barneygale/httpio#8]
```
>>> import httpio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frafra/.cache/pypoetry/virtualenvs/draft-2Uym0jAL-py3.9/lib64/python3.9/site-packages/httpio/__init__.py", line 229, in <module>
    from .asyncio import AsyncHTTPIOFileContextManagerMixin
  File "/home/frafra/.cache/pypoetry/virtualenvs/draft-2Uym0jAL-py3.9/lib64/python3.9/site-packages/httpio/asyncio.py", line 4, in <module>
    from httpio_async import AsyncHTTPIOFile, AsyncHTTPIOFileContextManagerMixin  # noqa: F401
  File "/home/frafra/.cache/pypoetry/virtualenvs/draft-2Uym0jAL-py3.9/lib64/python3.9/site-packages/httpio_async/__init__.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

https://github.com/barneygale/httpio/blob/18c1b98e3b36156477124139afa234800fc24634/setup.py#L7-L10

**Comment by samdbmg** [comment]
How are you installing this? Because the version sniffing code in setup.py should add aiohttp on python >= 3.6? (A quick test in a virtualenv while doing #9  shows it seems to install for me!)
https://github.com/barneygale/httpio/blob/18c1b98e3b36156477124139afa234800fc24634/setup.py#L12-L14
